### ISSUE TITLE
Feature Request - Set Current Without Saving em EEPROM

### ISSUE THREAD

**Issue by soloam** [firstof9/python-openevse-http#103]
Back on the old v2 API, there was a option to on the API to set the charging current without saving it into the EEPROM, this would set the current without saving it, and it would restore it on reboot.

This was very useful to use with automatic current algorithms, for example limit the charging current accordingly with the house consumption or solar panel production. Since this varies a lot the current, it would save the EEPROM from several writes.

This was accomplished with the command "$SC <amp> N". Basically the same command, but followed by the "N".

So my idea was if we could have a service that would set the charging current, but setting the "N" so that its send but not saved to the EEPROM. I tested this on my system, and this where the results:

> $SC 15
< $OK 15^04

> $GC
< $OK 6 32 15 15^17

> $SC 10 N
< $OK 10^01

> $GC
< $OK 6 32 10 15^12

Notice that in the second GC we have 10 and 15.

minamps: min allowed current capacity
hmaxamps: max hardware allowed current capacity MAX_CURRENT_CAPACITY_Ln
pilotamps: current capacity advertised by pilot
cmaxamps: max configured allowed current capacity (saved to EEPROM)

Thank you

**Comment by firstof9** [comment]
Will need to add `N` to the following line:

https://github.com/firstof9/python-openevse-http/blob/4ca30435333834f946afdf82dfb499e8f1a60251/openevsehttp/__init__.py#L525

**Comment by soloam** [comment]
Add N, but optional! Basicly we should be able to set the max current normally (on EEPROM) and temporarily (with N).

So 2 changes are needed, one on the library, and then some way to add it to Home Assistant!?

Thank you

**Comment by firstof9** [comment]
Implemented.

**Comment by soloam** [comment]
That's great news! When will it go live? I have to look at the Readme to see the method! Thank you

**Comment by firstof9** [comment]
The library will call a `set_override` and provide the amps as the override amperage value, this value stays in RAM and does not write to the EEPROM.

It is the recommended way to set this by the OpenEVSE devs.
