### ISSUE TITLE
Manual override Button not working 

### ISSUE THREAD

**Issue by soloam** [firstof9/python-openevse-http#104]
When I click the manual override button, or the sleep button, nothing happens, it returns to its previous state and nothing changes on openev.

I'm using version V4.1.5 of openevse and 2.1.7-b2 of the integration!

Thank you

**Comment by firstof9** [comment]
Odd, the API call looks unchanged.

I'll have to give this a test as well.

**Comment by soloam** [comment]
I created this issue here, but i fact this is related with the Home Assistant Integration, sorry abut that

**Comment by firstof9** [comment]
The integration hits the library to do the heavy lifting so technically either should be ok. I still have to test this.

**Comment by firstof9** [comment]
I just tested this with 4.1.5, and manual override is working as it should be.

**Comment by soloam** [comment]
This is working, sorry for the confusion, It was problem on my setup!

Issue can be closed! Tks
