### ISSUE TITLE
Plugin not working with last Home Assistant 2022.12.8 Frontend 20221213.1 -

### ISSUE THREAD

**Issue by NoRiCKaB3** [firstof9/python-openevse-http#149]
I updated HA few days ago, and since then the OpenEvse plugin is not working anymore.

On the logs I can see:

ERROR (MainThread) [custom_components.openevse] Error fetching OpenEVSE (openevse) data: 'utf-8' codec can't decode byte 0xff in position 158: invalid start byte

Also:

Logger: custom_components.openevse
Source: custom_components/openevse/__init__.py:242
Integration: OpenEVSE

Unexpected error fetching OpenEVSE (openevse).firmware data: 'version'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/openevse/__init__.py", line 242, in _async_update_data
    self._data = await self._manager.firmware_check()
  File "/usr/local/lib/python3.10/site-packages/openevsehttp/__main__.py", line 440, in firmware_check
    _LOGGER.debug("Detected firmware: %s", self._config["version"])
KeyError: 'version'

Failing with last 2.1.6 and 2.1.7b14

Regards.

**Comment by firstof9** [comment]
Actually looks like `version` does exist.

**Comment by firstof9** [comment]
I've just updated the firmware to `4.1.7` and I am unable to duplicate your error.

**Comment by NoRiCKaB3** [comment]
More destails about the error message:

  Logger: custom_components.openevse
Source: helpers/update_coordinator.py:201 
Integration: OpenEVSE 
First occurred: 19:39:32 (38 occurrences) 
Last logged: 20:20:58

Error fetching OpenEVSE (openevse) data: 'utf-8' codec can't decode byte 0xff in position 158: invalid start byte

Any clue about where to start looking for a fix?

**Comment by firstof9** [comment]
Check your actual `home-assistant.log` file.

**Comment by NoRiCKaB3** [comment]
Just replaced the ESP32 module with a new unit flashed to last version via USB, and it come to work again.

Regards.
