### ISSUE TITLE
Solar / Grid updates not updating grid_ie values

### ISSUE THREAD

**Issue by davethetallguy** [firstof9/python-openevse-http#258]
I see two impacts, but I think they are part of the same potential bug: 

Impact 1: It appears that updates are not pushed via POST unless both sensors are provided in configuration.
Impact 2: The grid_ie value never seems to update on the ESP32_WiFi_V4.x part (this could be a bug in either system)

The divert mode on Openevse operates on **either** solar production or grid export. (Screenshot below) The documentation for this option in ESP32_WiFi_V4.x says in part: 

- body can contain {"solar": value} **_or_** {"grid_ie": value} in watt. (my emphasis)

@jeremypoulter might need to comment if the "and" implementation is problematic, but I note that only the solar parameter is updated on the OpenEVSE device, grid_ie parameter remains at zero, when viewed via /status 

Update from HA Debug: 

2023-07-31 15:04:00.778 DEBUG (MainThread) [custom_components.openevse] Sending sensor data to OpenEVSE: (solar: -1206) (grid: 1159)
2023-07-31 15:04:00.778 DEBUG (MainThread) [openevsehttp.__main__] Posting self-production: {'solar': -1206, 'grid': 1159}
2023-07-31 15:04:00.779 DEBUG (MainThread) [openevsehttp.__main__] Connecting to http://openevse.local/status with data: {'solar': -1206, 'grid': 1159} rapi: None using method post
2023-07-31 15:04:00.870 DEBUG (MainThread) [openevsehttp.__main__] Self-production response: {'solar': 1234, 'grid': 1159}
2023-07-31 15:04:00.872 DEBUG (MainThread) [openevsehttp.__main__] Self-production response: {'solar': -1206, 'grid': 1159}

from openevse.local/status:
... "solar":-1206,"grid_ie":0 ...

I don't know if presenting only one or the other value will enable grid_ie to update correctly?  Again, I believe that would be the expected state, since on the self-production screen one configures for an either / or condition.

(Screenshot was not taken at the same time as the update in the debug)
<img width="732" alt="Screenshot 2023-07-31 at 3 10 19 PM" src="https://github.com/firstof9/openevse/assets/64752714/82abdaf2-5f43-44b1-8e77-0e03955d8064">

Thanks as always for the great help.

**Comment by firstof9** [comment]
Give it about 15-30 mins, and you can modify the `manifest.json` file in `/config/custom_components/openevse/` directory and bump the library from `0.1.53` to `0.1.54` and restart HA.

I'll version bump the integration shortly as well.

**Comment by davethetallguy** [comment]
I'm still seeing the same behaviors - no updates unless both sensors are
provided, and then the updates only update status of "solar" on the actual
EVSE device.

Note that I did some direct POST tests to the OpenEVSE device. Including
only one of the tags (solar or grid_ie) updated the respective state.
Sending both in one POST only updated whichever was the first presented,
the second remained unchanged. One could argue this is a bug in
ESP32_WiFi_V4.x, except the documentation does indicate a POST should
contain one OR the other of the values.

I'm running ESP32_WiFi_V4.x, V.4.2.2, any chance you're using something
later in your configuration?

**Comment by jeremypoulter** [comment]
If both values are sent then just the solar will be processed: https://github.com/OpenEVSE/ESP32_WiFi_V4.x/blob/master/src/web_server.cpp#L460

I guess we could remove the `else` but not sure what the value of sending both of them is.

**Comment by firstof9** [comment]
> If both values are sent then just the solar will be processed

Thanks for clarification.

@davethetallguy I'll drop an update shortly.

**Comment by firstof9** [comment]
We should be good in the latest version, I have the integration prefer grid import/export over solar, if both are defined.
I also adjusted the wording in the configuration screen.

**Comment by davethetallguy** [comment]
Nice!  Working as requested!  

(Where's your "buy me a coffee" link?)

**Comment by firstof9** [comment]
It's listed on the readme for the integration: https://github.com/firstof9/openevse
